# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui\qtilesdialogbase.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(609, 708)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea = QtWidgets.QScrollArea(Dialog)
        self.scrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 609, 708))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.rbOutputZip = QtWidgets.QRadioButton(self.groupBox)
        self.rbOutputZip.setObjectName("rbOutputZip")
        self.gridLayout.addWidget(self.rbOutputZip, 0, 0, 1, 1)
        self.leZipFileName = QtWidgets.QLineEdit(self.groupBox)
        self.leZipFileName.setObjectName("leZipFileName")
        self.gridLayout.addWidget(self.leZipFileName, 0, 1, 1, 1)
        self.btnBrowse = QtWidgets.QPushButton(self.groupBox)
        self.btnBrowse.setObjectName("btnBrowse")
        self.gridLayout.addWidget(self.btnBrowse, 0, 2, 2, 1)
        self.rbOutputDir = QtWidgets.QRadioButton(self.groupBox)
        self.rbOutputDir.setObjectName("rbOutputDir")
        self.gridLayout.addWidget(self.rbOutputDir, 1, 0, 1, 1)
        self.leDirectoryName = QtWidgets.QLineEdit(self.groupBox)
        self.leDirectoryName.setObjectName("leDirectoryName")
        self.gridLayout.addWidget(self.leDirectoryName, 1, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 0, 1, 1)
        self.leRootDir = QtWidgets.QLineEdit(self.groupBox)
        self.leRootDir.setObjectName("leRootDir")
        self.gridLayout.addWidget(self.leRootDir, 2, 1, 1, 2)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.rbExtentCanvas = QtWidgets.QRadioButton(self.groupBox_2)
        self.rbExtentCanvas.setObjectName("rbExtentCanvas")
        self.gridLayout_2.addWidget(self.rbExtentCanvas, 0, 0, 1, 1)
        self.rbExtentFull = QtWidgets.QRadioButton(self.groupBox_2)
        self.rbExtentFull.setObjectName("rbExtentFull")
        self.gridLayout_2.addWidget(self.rbExtentFull, 1, 0, 1, 1)
        self.rbExtentLayer = QtWidgets.QRadioButton(self.groupBox_2)
        self.rbExtentLayer.setObjectName("rbExtentLayer")
        self.gridLayout_2.addWidget(self.rbExtentLayer, 2, 0, 1, 1)
        self.cmbLayers = QtWidgets.QComboBox(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbLayers.sizePolicy().hasHeightForWidth())
        self.cmbLayers.setSizePolicy(sizePolicy)
        self.cmbLayers.setObjectName("cmbLayers")
        self.gridLayout_2.addWidget(self.cmbLayers, 2, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBox_2)
        self.frame = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.groupBox_3 = QtWidgets.QGroupBox(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label = QtWidgets.QLabel(self.groupBox_3)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 2, 0, 1, 1, QtCore.Qt.AlignLeft)
        self.spnZoomMax = QtWidgets.QSpinBox(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spnZoomMax.sizePolicy().hasHeightForWidth())
        self.spnZoomMax.setSizePolicy(sizePolicy)
        self.spnZoomMax.setMinimum(0)
        self.spnZoomMax.setMaximum(40)
        self.spnZoomMax.setProperty("value", 18)
        self.spnZoomMax.setObjectName("spnZoomMax")
        self.gridLayout_3.addWidget(self.spnZoomMax, 2, 1, 1, 1)
        self.spnZoomMin = QtWidgets.QSpinBox(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spnZoomMin.sizePolicy().hasHeightForWidth())
        self.spnZoomMin.setSizePolicy(sizePolicy)
        self.spnZoomMin.setMaximum(40)
        self.spnZoomMin.setObjectName("spnZoomMin")
        self.gridLayout_3.addWidget(self.spnZoomMin, 0, 1, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox_3, 0, 0, 1, 1)
        self.grpMetaTiling = QtWidgets.QGroupBox(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.grpMetaTiling.sizePolicy().hasHeightForWidth())
        self.grpMetaTiling.setSizePolicy(sizePolicy)
        self.grpMetaTiling.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.grpMetaTiling.setObjectName("grpMetaTiling")
        self.chkUseMetatiling = QtWidgets.QCheckBox(self.grpMetaTiling)
        self.chkUseMetatiling.setGeometry(QtCore.QRect(20, 20, 111, 17))
        self.chkUseMetatiling.setChecked(True)
        self.chkUseMetatiling.setObjectName("chkUseMetatiling")
        self.chkBufferMetatiles = QtWidgets.QCheckBox(self.grpMetaTiling)
        self.chkBufferMetatiles.setGeometry(QtCore.QRect(140, 20, 111, 17))
        self.chkBufferMetatiles.setChecked(True)
        self.chkBufferMetatiles.setObjectName("chkBufferMetatiles")
        self.spnMetaWidth = QtWidgets.QSpinBox(self.grpMetaTiling)
        self.spnMetaWidth.setGeometry(QtCore.QRect(60, 50, 41, 22))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spnMetaWidth.sizePolicy().hasHeightForWidth())
        self.spnMetaWidth.setSizePolicy(sizePolicy)
        self.spnMetaWidth.setMinimum(2)
        self.spnMetaWidth.setObjectName("spnMetaWidth")
        self.spnMetaHeight = QtWidgets.QSpinBox(self.grpMetaTiling)
        self.spnMetaHeight.setGeometry(QtCore.QRect(150, 50, 41, 22))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spnMetaHeight.sizePolicy().hasHeightForWidth())
        self.spnMetaHeight.setSizePolicy(sizePolicy)
        self.spnMetaHeight.setMinimum(2)
        self.spnMetaHeight.setObjectName("spnMetaHeight")
        self.label_9 = QtWidgets.QLabel(self.grpMetaTiling)
        self.label_9.setGeometry(QtCore.QRect(20, 50, 31, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.grpMetaTiling)
        self.label_10.setGeometry(QtCore.QRect(110, 50, 31, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setObjectName("label_10")
        self.gridLayout_4.addWidget(self.grpMetaTiling, 0, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.frame)
        self.grpParameters = QgsCollapsibleGroupBox(self.scrollAreaWidgetContents)
        self.grpParameters.setProperty("collapsed", True)
        self.grpParameters.setProperty("saveCollapsedState", True)
        self.grpParameters.setObjectName("grpParameters")
        self.gridlayout = QtWidgets.QGridLayout(self.grpParameters)
        self.gridlayout.setObjectName("gridlayout")
        self.lblHeight = QtWidgets.QLabel(self.grpParameters)
        self.lblHeight.setEnabled(True)
        self.lblHeight.setObjectName("lblHeight")
        self.gridlayout.addWidget(self.lblHeight, 1, 0, 1, 1)
        self.spnTileWidth = QtWidgets.QSpinBox(self.grpParameters)
        self.spnTileWidth.setMinimum(128)
        self.spnTileWidth.setMaximum(2048)
        self.spnTileWidth.setProperty("value", 256)
        self.spnTileWidth.setObjectName("spnTileWidth")
        self.gridlayout.addWidget(self.spnTileWidth, 0, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.grpParameters)
        self.label_6.setObjectName("label_6")
        self.gridlayout.addWidget(self.label_6, 3, 0, 1, 1)
        self.chkTMSConvention = QtWidgets.QCheckBox(self.grpParameters)
        self.chkTMSConvention.setObjectName("chkTMSConvention")
        self.gridlayout.addWidget(self.chkTMSConvention, 7, 0, 1, 1)
        self.spnTileHeight = QtWidgets.QSpinBox(self.grpParameters)
        self.spnTileHeight.setEnabled(True)
        self.spnTileHeight.setMinimum(128)
        self.spnTileHeight.setMaximum(2048)
        self.spnTileHeight.setProperty("value", 256)
        self.spnTileHeight.setObjectName("spnTileHeight")
        self.gridlayout.addWidget(self.spnTileHeight, 1, 1, 1, 1)
        self.chkLockRatio = QtWidgets.QCheckBox(self.grpParameters)
        self.chkLockRatio.setObjectName("chkLockRatio")
        self.gridlayout.addWidget(self.chkLockRatio, 0, 2, 2, 1)
        self.chkAntialiasing = QtWidgets.QCheckBox(self.grpParameters)
        self.chkAntialiasing.setObjectName("chkAntialiasing")
        self.gridlayout.addWidget(self.chkAntialiasing, 6, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.grpParameters)
        self.label_3.setObjectName("label_3")
        self.gridlayout.addWidget(self.label_3, 0, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.grpParameters)
        self.label_5.setObjectName("label_5")
        self.gridlayout.addWidget(self.label_5, 4, 0, 1, 1)
        self.cmbFormat = QtWidgets.QComboBox(self.grpParameters)
        self.cmbFormat.setObjectName("cmbFormat")
        self.cmbFormat.addItem("")
        self.cmbFormat.addItem("")
        self.gridlayout.addWidget(self.cmbFormat, 3, 1, 1, 2)
        self.spnTransparency = QtWidgets.QSpinBox(self.grpParameters)
        self.spnTransparency.setMaximum(100)
        self.spnTransparency.setProperty("value", 100)
        self.spnTransparency.setObjectName("spnTransparency")
        self.gridlayout.addWidget(self.spnTransparency, 4, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.grpParameters)
        self.label_7.setObjectName("label_7")
        self.gridlayout.addWidget(self.label_7, 5, 0, 1, 1)
        self.spnQuality = QtWidgets.QSpinBox(self.grpParameters)
        self.spnQuality.setMinimum(0)
        self.spnQuality.setMaximum(100)
        self.spnQuality.setProperty("value", 0)
        self.spnQuality.setObjectName("spnQuality")
        self.gridlayout.addWidget(self.spnQuality, 5, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.grpParameters)
        self.label_8.setObjectName("label_8")
        self.gridlayout.addWidget(self.label_8, 5, 2, 1, 1)
        self.chkFeatures = QtWidgets.QCheckBox(self.grpParameters)
        self.chkFeatures.setObjectName("chkFeatures")
        self.gridlayout.addWidget(self.chkFeatures, 10, 0, 1, 3)
        self.chkWriteMapurl = QtWidgets.QCheckBox(self.grpParameters)
        self.chkWriteMapurl.setObjectName("chkWriteMapurl")
        self.gridlayout.addWidget(self.chkWriteMapurl, 8, 0, 1, 1)
        self.chkWriteViewer = QtWidgets.QCheckBox(self.grpParameters)
        self.chkWriteViewer.setObjectName("chkWriteViewer")
        self.gridlayout.addWidget(self.chkWriteViewer, 9, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.grpParameters)
        self.label_11.setObjectName("label_11")
        self.gridlayout.addWidget(self.label_11, 4, 2, 1, 1)
        self.verticalLayout_2.addWidget(self.grpParameters)
        self.frame_2 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_5.setContentsMargins(-1, 0, -1, -1)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.progressBar = QtWidgets.QProgressBar(self.frame_2)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setTextVisible(True)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout_5.addWidget(self.progressBar, 0, 0, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(self.frame_2)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Close|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout_5.addWidget(self.buttonBox, 1, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.frame_2)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "QMetaTiles"))
        self.groupBox.setTitle(_translate("Dialog", "Output"))
        self.rbOutputZip.setText(_translate("Dialog", "File"))
        self.btnBrowse.setText(_translate("Dialog", "Browse..."))
        self.rbOutputDir.setText(_translate("Dialog", "Directory"))
        self.label_4.setText(_translate("Dialog", "Tileset name"))
        self.groupBox_2.setTitle(_translate("Dialog", "Extent"))
        self.rbExtentCanvas.setText(_translate("Dialog", "Canvas extent"))
        self.rbExtentFull.setText(_translate("Dialog", "Full extent"))
        self.rbExtentLayer.setText(_translate("Dialog", "Layer extent"))
        self.groupBox_3.setTitle(_translate("Dialog", "Zoom"))
        self.label.setText(_translate("Dialog", "Minimum zoom"))
        self.label_2.setText(_translate("Dialog", "Maximum zoom"))
        self.grpMetaTiling.setTitle(_translate("Dialog", "Metatiling"))
        self.chkUseMetatiling.setText(_translate("Dialog", "Enable Metatiling"))
        self.chkBufferMetatiles.setText(_translate("Dialog", "Buffer Metatiles"))
        self.label_9.setText(_translate("Dialog", "Width"))
        self.label_10.setText(_translate("Dialog", "Height"))
        self.grpParameters.setTitle(_translate("Dialog", "Parameters"))
        self.lblHeight.setText(_translate("Dialog", "Tile height"))
        self.label_6.setText(_translate("Dialog", "Format"))
        self.chkTMSConvention.setText(_translate("Dialog", "Use TMS tiles convention (Slippy Map by default)"))
        self.chkLockRatio.setText(_translate("Dialog", "Lock 1:1 ratio"))
        self.chkAntialiasing.setText(_translate("Dialog", "Make lines appear less jagged at the expence of some drawing performance"))
        self.label_3.setText(_translate("Dialog", "Tile width"))
        self.label_5.setText(_translate("Dialog", "Background transparency"))
        self.cmbFormat.setItemText(0, _translate("Dialog", "PNG"))
        self.cmbFormat.setItemText(1, _translate("Dialog", "JPG"))
        self.label_7.setText(_translate("Dialog", "Quality"))
        self.label_8.setText(_translate("Dialog", "(0-100)"))
        self.chkFeatures.setText(_translate("Dialog", "Export LatLonGO® features and metadata"))
        self.chkWriteMapurl.setText(_translate("Dialog", "Write .mapurl file"))
        self.chkWriteViewer.setText(_translate("Dialog", "Write Leaflet-based viewer"))
        self.label_11.setText(_translate("Dialog", "(0-100)"))

from qgis.gui import QgsCollapsibleGroupBox
